version: 2.1

jobs:
  test:
    docker:
      - image: circleci/ruby:2.7.1
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    steps:
      - checkout
      - run:
          name: Install env dependencies
          command: |
            sudo apt-get update --allow-releaseinfo-change
            sudo apt-get install cmake pkg-config
      - run:
          name: Install Ruby gems
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run:
          name: Set up test output directory
          command: sudo install -o circleci -d ~/rspec
      - run:
          name: RSpec
          command: |
            bundle exec rspec \
              --color \
              --require spec_helper \
              --format documentation \
              --format RspecJunitFormatter \
              --out ~/rspec/rspec.xml
  push_to_rubygems:
    docker:
      - image: circleci/ruby:2.7.1
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    steps:
      - checkout
      - run:
          name: Create .gem/credentials file
          command: |
            mkdir ~/.gem
            echo "---
              :rubygems_api_key: $RUBYGEMS_API_KEY
            " > ~/.gem/credentials
            chmod 600 ~/.gem/credentials
      - run:
          name: Release pronto-commentator
          command: |
            gem build pronto-commentator
            gem push pronto-commentator-*.gem

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test:
          filters:
            tags:
              only:
                - /^v.*/
          context:
            - DockerHub
      - push_to_rubygems:
          requires:
            - test
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - /^v.*/
          context:
            - DockerHub
